import assert from 'node:assert/strict';
import { test } from 'node:test';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { createRequire } from 'node:module';
import { _electron, expect } from '@playwright/test';
import { companionFixture } from './helpers/companion-fixture.ts';

const packaged = process.env.REPO_CHAP_DESKTOP_EXECUTABLE;
const executablePath: string = packaged ?? createRequire(resolve('apps/desktop/package.json'))('electron');
const cli = resolve('apps/cli/dist/cli.js');

test('Electron follows a normal agent through workflow edits, simulation, guidance, real PRs and restart', { timeout: 150_000 }, async t => {
  const f = await companionFixture(); t.after(f.cleanup);
  const proof = process.env.REPO_CHAP_DESKTOP_PROOF;
  if (proof) await mkdir(proof, { recursive: true });
  const env = { ...process.env, REPO_CHAP_DESKTOP_CONTROL: f.control, REPO_CHAP_DESKTOP_DATA: f.data };
  const launch = () => _electron.launch({ executablePath, args: packaged ? [] : [resolve('apps/desktop')], env });
  let electron = await launch(); t.after(async () => { await electron.close().catch(() => {}); });
  let page = await electron.firstWindow();
  const errors: string[] = [], requests: string[] = [];
  page.on('pageerror', error => errors.push(error.message)); page.on('request', request => { if (/^https?:/.test(request.url())) requests.push(request.url()); });
  const command = async (...args: string[]) => {
    const result = await promisify(execFile)(process.execPath, [cli, 'desktop', ...args, '--repo-root', f.repository, '--json'], { env });
    return JSON.parse(result.stdout).state;
  };
  await expect(page.locator('#welcome')).toBeVisible();
  await command('open', '--workflow', f.pkg.workflowPath);
  await expect(page.locator('#workflow-title')).toHaveText('team-pr');
  await expect(page.locator('#overview')).toBeVisible();
  assert.equal(await page.locator('textarea').count(), 0);
  assert.equal(await page.evaluate(() => typeof (window as any).repoChapConversation), 'undefined');
  assert.equal(await page.evaluate(() => typeof (window as any).require), 'undefined');
  assert.ok(await page.locator('button:visible').count() <= 3);
  if (proof) await page.screenshot({ path: join(proof, 'overview.png'), fullPage: true });
  await command('highlight', '--target', 'rule:reviewer_active', '--style', 'arrow', '--text', 'The workflow waits here while the reviewer is working.', '--seconds', '20');
  await expect(page.locator('#guidance')).toContainText('The workflow waits here');
  await expect(page.locator('#guidance-arrow')).toBeVisible();
  await expect(page.locator('[data-target="rule:reviewer_active"]')).toHaveClass(/agent-target/);
  if (proof) await page.screenshot({ path: join(proof, 'agent-guidance.png'), fullPage: true });
  await page.keyboard.press('Escape'); await expect(page.locator('#guidance')).toBeHidden();
  await command('show', '--target', 'action:review');
  await expect(page.locator('[data-target="action:review"]')).toHaveAttribute('open', '');
  await command('highlight', '--target', 'action:review', '--text', '<script>plain text</script>', '--seconds', '1');
  await expect(page.locator('#guidance')).toContainText('<script>plain text</script>');
  assert.equal(await page.locator('#guidance script').count(), 0);
  await expect(page.locator('#guidance')).toBeHidden({ timeout: 4000 });
  await command('simulate', '--fixture', f.fixturePath);
  await expect(page.locator('#simulation')).toBeVisible();
  assert.equal(await page.evaluate(() => scrollY), 0);
  await expect(page.locator('#result')).toContainText('Test passed');
  await expect(page.getByRole('table', { name: 'Expected and actual outcomes' })).toBeVisible();
  const prompt = f.pkg.files.find(file => file.path.endsWith('/review.md'))!;
  await writeFile(join(f.repository, prompt.path), prompt.text + '\nCheck the boundary condition.\n');
  await expect(page.locator('#result')).toContainText('Files changed.', { timeout: 10_000 });
  await page.locator('#simulate').click(); await expect(page.locator('#result')).not.toContainText('Files changed.');
  await writeFile(f.workflow, '{ invalid');
  await expect(page.locator('#diagnostics')).toBeVisible({ timeout: 10_000 });
  await expect(page.locator('#simulate')).toBeDisabled(); await expect(page.locator('#result')).toContainText('Files changed.');
  assert.equal(await readFile(f.workflow, 'utf8'), '{ invalid');
  await writeFile(f.workflow, JSON.stringify(f.pkg.workflow));
  await expect(page.locator('#diagnostics')).toBeHidden({ timeout: 10_000 });
  await command('simulate', '--capture', f.capture.directory);
  await expect(page.locator('#pr-mode')).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('#input-summary')).toContainText('willow-labs/sample-project #42');
  await expect(page.locator('#input-note')).toContainText('Current GitHub state has not been checked.');
  await expect(page.locator('#input-note')).toContainText('earlier workflow');
  if (proof) await page.screenshot({ path: join(proof, 'captured-pr.png'), fullPage: true });
  await page.locator('#tests-mode').click(); await expect(page.locator('#result')).toContainText('Test passed');
  await page.locator('#overview-tab').focus(); await page.keyboard.press('Enter'); await expect(page.locator('#overview')).toBeVisible();
  const alternate = 'another.workflow.json'; await writeFile(join(f.repository, alternate), await readFile('skills/repo-chap-workflows/assets/workflow.json', 'utf8'));
  await expect(page.locator('#workflow-select option')).toHaveCount(2, { timeout: 10_000 });
  await page.locator('#workflow-select').selectOption(alternate); await expect(page.locator('#workflow-title')).toHaveText('repository-pr');
  assert.equal((await command('status')).simulation, null);
  for (const [width, height] of [[1024, 768], [390, 844]]) {
    await electron.evaluate(({ BrowserWindow }, bounds) => BrowserWindow.getAllWindows()[0]!.setBounds(bounds), { width, height });
    await expect.poll(() => page.evaluate(() => innerWidth)).toBe(width);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1));
    if (proof) await page.screenshot({ path: join(proof, `overview-${width}.png`), fullPage: true });
  }
  assert.deepEqual(errors, []); assert.deepEqual(requests, []);
  await expect.poll(async () => JSON.parse(await readFile(join(f.data, 'companion/selection.json'), 'utf8')).workflowPath).toBe(alternate);
  await electron.close();
  electron = await launch(); page = await electron.firstWindow();
  await expect(page.locator('#workflow-title')).toHaveText('repository-pr');
  assert.equal((await command('status')).workflowPath, alternate);
  await electron.close();
});

test('an empty repository discovers the agent-created workflow and a cancelled picker preserves selection', { timeout: 40_000 }, async t => {
  const f = await companionFixture(); t.after(f.cleanup);
  const empty = join(f.temporary, 'new-project'); await mkdir(empty);
  const electron = await _electron.launch({ executablePath, args: packaged ? [] : [resolve('apps/desktop')], env: { ...process.env, REPO_CHAP_DESKTOP_CONTROL: f.control, REPO_CHAP_DESKTOP_DATA: f.data } });
  t.after(() => electron.close()); const page = await electron.firstWindow();
  await page.evaluate(async root => window.repoChap.command({ kind: 'open', repositoryRoot: root }), empty);
  await expect(page.locator('#empty')).toBeVisible();
  await writeFile(join(empty, 'workflow.json'), await readFile('skills/repo-chap-workflows/assets/workflow.json', 'utf8'));
  await expect(page.locator('#workflow-title')).toHaveText('repository-pr', { timeout: 10_000 });
  await electron.evaluate(({ dialog }) => { dialog.showOpenDialog = async () => ({ canceled: true, filePaths: [] }); });
  await page.locator('#open-repository').click(); await expect(page.locator('#workflow-title')).toHaveText('repository-pr');
});
