import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createRequire } from 'node:module';
import { _electron, expect } from '@playwright/test';

const executablePath: string = createRequire(resolve('apps/desktop/package.json'))('electron');
test('new users choose and save a provider without a file picker, and reuse it after restart', { timeout: 60_000 }, async t => {
  const directory = await mkdtemp(join(tmpdir(), 'repo-chap-provider-ui-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const bin = join(directory, 'bin'); await mkdir(bin);
  await writeFile(join(bin, 'codex'), `#!${process.execPath}\nconsole.log(JSON.stringify({models:[{slug:'fictional-codex',display_name:'Fictional Codex'}]}));\n`, { mode: 0o700 });
  await writeFile(join(bin, 'claude'), `#!${process.execPath}\nconsole.log('fictional-version');\n`, { mode: 0o700 });
  const args = [resolve('apps/desktop'), '--workflow', resolve('docs/pr-workflows/examples/team-pr/workflow.json')];
  const env: Record<string, string> = { PATH: `${bin}:${process.env.PATH}`, REPO_CHAP_DESKTOP_DATA: join(directory, 'data') };
  for (const key of ['HOME', 'DISPLAY', 'XAUTHORITY', 'XDG_RUNTIME_DIR', 'DBUS_SESSION_BUS_ADDRESS']) if (process.env[key]) env[key] = process.env[key]!;
  let electron = await _electron.launch({ executablePath, args, env });
  t.after(async () => { await electron.evaluate(({ BrowserWindow }) => { for (const window of BrowserWindow.getAllWindows()) window.destroy(); }).catch(() => {}); await electron.close().catch(() => {}); });
  let page = await electron.firstWindow();
  await electron.evaluate(({ dialog }) => { dialog.showOpenDialog = async () => { throw new Error('Setup must not open a file picker.'); }; });
  await page.locator('#conversation-tab').click();
  await expect(page.locator('#setup-save')).toBeDisabled();
  await page.locator('#setup-provider').selectOption('codex');
  await expect(page.locator('#setup-model')).toHaveValue('fictional-codex');
  await page.locator('#setup-save').click();
  await expect(page.locator('#conversation-selected-provider')).toContainText('fictional-codex');
  await page.locator('#conversation-question').fill('A question ready to send.');
  await expect(page.locator('#conversation-send')).toBeEnabled();
  const saved = JSON.parse(await readFile(join(directory, 'data/providers.json'), 'utf8'));
  assert.equal(saved.profiles.desktop_codex.model, 'fictional-codex');
  await page.locator('#setup-provider').selectOption('claude');
  await expect(page.locator('#setup-model')).toHaveValue('sonnet');
  await page.locator('#setup-model').selectOption('opus');
  await page.locator('#setup-save').click();
  await expect(page.locator('#conversation-selected-provider')).toContainText('Claude · opus');
  const proof = await mkdtemp(join(tmpdir(), 'repo-chap-provider-proof-'));
  await page.screenshot({ path: join(proof, 'setup.png'), fullPage: true });
  await page.setViewportSize({ width: 800, height: 850 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await electron.evaluate(({ BrowserWindow }) => { for (const window of BrowserWindow.getAllWindows()) window.destroy(); });
  await electron.close();
  electron = await _electron.launch({ executablePath, args, env }); page = await electron.firstWindow();
  await page.locator('#conversation-tab').click();
  await page.locator('#conversation-profile').selectOption('desktop_claude');
  await page.locator('#conversation-use-profile').click();
  await expect(page.locator('#conversation-selected-provider')).toContainText('Claude · opus');
  await writeFile(join(bin, 'codex'), `#!${process.execPath}\nprocess.exit(1);\n`, { mode: 0o700 });
  await page.locator('#setup-provider').selectOption('codex');
  await expect(page.locator('#setup-status')).toContainText('Install it');
  await expect(page.locator('#setup-retry')).toBeVisible();
  await expect(page.locator('#setup-save')).toBeDisabled();
  await expect(page.locator('#conversation-selected-provider')).toContainText('Claude · opus');
});
