import assert from 'node:assert/strict';
import { test } from 'node:test';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { createRequire } from 'node:module';
import { _electron, expect } from '@playwright/test';
import { companionFixture } from './helpers/companion-fixture.ts';

const packaged = process.env.REPO_CHAP_DESKTOP_EXECUTABLE;
const executablePath: string = packaged ?? createRequire(resolve('apps/desktop/package.json'))('electron');
const cli = resolve('apps/cli/dist/cli.js');

test('Electron follows a normal agent through workflow edits, simulation, guidance, real PRs and restart', { timeout: 150_000 }, async t => {
  const f = await companionFixture(); t.after(f.cleanup);
  const proof = process.env.REPO_CHAP_DESKTOP_PROOF;
  if (proof) await mkdir(proof, { recursive: true });
  const env = { ...process.env, REPO_CHAP_DESKTOP_CONTROL: f.control, REPO_CHAP_DESKTOP_DATA: f.data };
  const launch = () => _electron.launch({ executablePath, args: packaged ? [] : [resolve('apps/desktop')], env });
  let electron = await launch(); t.after(async () => { await electron.close().catch(() => {}); });
  let page = await electron.firstWindow();
  const errors: string[] = [], requests: string[] = [];
  page.on('pageerror', error => errors.push(error.message)); page.on('request', request => { if (/^https?:/.test(request.url())) requests.push(request.url()); });
  const command = async (...args: string[]) => {
    const result = await promisify(execFile)(process.execPath, [cli, 'desktop', ...args, '--repo-root', f.repository, '--json'], { env });
    return JSON.parse(result.stdout).state;
  };
  await expect(page.locator('#welcome')).toBeVisible();
  await expect(page.locator('#repository-name')).toHaveText('Open repository');
  assert.ok(await electron.evaluate(({ Menu }) => Menu.getApplicationMenu()?.items.some(item => item.role?.toLowerCase() === 'windowmenu')));

  await command('open', '--workflow', f.pkg.workflowPath);
  await expect(page.locator('#workflow-select')).toHaveValue(f.pkg.workflowPath);
  await expect(page.locator('#overview')).toBeVisible();
  await expect(page.locator('.canvas-node[data-id="group:repair"]')).toContainText('3 actions');
  await page.getByRole('button', { name: 'Show whole workflow', exact: true }).click();
  const world = page.locator('.canvas-world');
  const beforePan = await world.getAttribute('style');
  await page.locator('.canvas-viewport').focus(); await page.keyboard.press('ArrowRight');
  assert.notEqual(await world.getAttribute('style'), beforePan);
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  await page.getByRole('button', { name: 'Show whole workflow', exact: true }).click();
  await page.locator('[data-id="group:repair"]').click();
  await expect(page.locator('.canvas-inspector')).toContainText('Failed → Ask a person in Slack');
  await page.getByRole('button', { name: 'Expand section', exact: true }).click();
  await expect(page.locator('[data-target="action:resolve_conflict"]')).toBeVisible();
  await command('show', '--target', 'action:park');
  await expect(page.locator('.canvas-inspector')).toContainText('Failed → Needs attention');
  await command('show', '--target', 'action:push_candidate');
  await expect(page.locator('[data-target="action:push_candidate"]')).toContainText('Push the checked commit');
  await command('show', '--target', 'rule:repair_waiting_human');
  const nested = page.locator('[data-target="rule:repair_waiting_human"]');
  await expect(nested).toHaveAttribute('open', '');
  await expect(nested).toContainText('All of'); await expect(nested).toContainText('Any of');
  await command('show', '--target', 'action:review');
  await expect(page.locator('.canvas-inspector')).toContainText('prompts/review.md');
  await expect(page.locator('.canvas-configuration')).toHaveAttribute('open', '');
  assert.equal(await page.locator('textarea').count(), 0);
  assert.equal(await page.evaluate(() => typeof (window as any).repoChapConversation), 'undefined');
  assert.equal(await page.evaluate(() => typeof (window as any).require), 'undefined');
  await page.locator('#available-tab').click();
  await expect(page.locator('#available')).toBeVisible();
  await expect(page.locator('#action-catalogue')).toContainText('Publish the review on GitHub');
  await expect(page.locator('#action-catalogue')).toContainText('Update GitHub labels');
  await expect(page.locator('#condition-catalogue')).toContainText('GitHub details');
  if (proof) await page.screenshot({ path: join(proof, 'available.png'), fullPage: true });
  await page.locator('#overview-tab').click();
  const converging = structuredClone(f.pkg.workflow);
  converging.rules.unshift({ id: 'branching_example', when: { field: 'facts.conflict', op: 'eq', value: true }, action: 'branch_start' });
  converging.actions.branch_start = { ...structuredClone(converging.actions.review!), onSuccess: 'branch_left', onFailure: 'branch_right' };
  converging.actions.branch_left = { ...structuredClone(converging.actions.classify!), onSuccess: 'branch_join', onFailure: 'branch_join' };
  converging.actions.branch_right = { ...structuredClone(converging.actions.review!), onSuccess: 'branch_join', onFailure: 'branch_join' };
  converging.actions.branch_join = structuredClone(converging.actions.park!);
  await writeFile(f.workflow, JSON.stringify(converging));
  await expect(page.locator('[data-id="group:review"]')).toContainText('5 actions', { timeout: 10_000 });
  await command('show', '--target', 'action:branch_right');
  await expect(page.locator('[data-target="action:branch_right"]')).toBeVisible();
  await command('show', '--target', 'action:branch_join');
  await expect(page.locator('[data-target="action:branch_join"]')).toBeVisible();
  assert.equal(await page.locator('[data-target="action:branch_join"]').count(), 1);
  assert.equal(await page.locator('[data-edge-target="branch_join"]').count(), 4);
  await writeFile(f.workflow, JSON.stringify(f.pkg.workflow));
  await expect(page.locator('[data-id="group:review"]')).toContainText('2 actions', { timeout: 10_000 });
  const cyclic = structuredClone(f.pkg.workflow);
  cyclic.actions.review!.onSuccess = 'review';
  await writeFile(f.workflow, JSON.stringify(cyclic));
  await expect.poll(async () => (await command('status')).workflow.actions.review.onSuccess).toBe('review');
  await command('show', '--target', 'action:review');
  await expect(page.locator('[data-edge-target="review"][data-edge-loop="true"]')).toHaveCount(1, { timeout: 10_000 });
  assert.equal(await page.locator('[data-target="action:review"]').count(), 1);
  await writeFile(f.workflow, JSON.stringify(f.pkg.workflow));
  await expect(page.locator('[data-edge-loop="true"]')).toHaveCount(0, { timeout: 10_000 });
  if (proof) await page.screenshot({ path: join(proof, 'overview.png'), fullPage: true });
  await command('highlight', '--target', 'rule:reviewer_active', '--style', 'arrow', '--text', 'The workflow waits here while the reviewer is working.', '--seconds', '20');
  await expect(page.locator('#guidance')).toContainText('The workflow waits here');
  await expect(page.locator('#guidance-arrow')).toBeVisible();
  await expect(page.locator('[data-target="rule:reviewer_active"]')).toHaveClass(/agent-target/);
  if (proof) await page.screenshot({ path: join(proof, 'agent-guidance.png'), fullPage: true });
  await page.keyboard.press('Escape'); await expect(page.locator('#guidance')).toBeHidden();
  await command('show', '--target', 'action:review');
  await expect(page.locator('[data-target="action:review"]')).toHaveClass(/agent-target/);
  await expect(page.locator('.canvas-configuration')).toHaveAttribute('open', '');
  await electron.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]!.setBounds({ width: 820, height: 760 }));
  await expect(page.locator('[data-target="action:review"]')).toHaveClass(/agent-target/);
  await command('highlight', '--target', 'action:review', '--text', '<script>plain text</script>', '--seconds', '1');
  await expect(page.locator('#guidance')).toContainText('<script>plain text</script>');
  assert.equal(await page.locator('#guidance script').count(), 0);
  await expect(page.locator('#guidance')).toBeHidden({ timeout: 4000 });
  await command('simulate', '--fixture', f.fixturePath);
  await expect(page.locator('#simulation')).toBeVisible();
  assert.equal(await page.evaluate(() => scrollY), 0);
  await expect(page.locator('#result')).toContainText('Test passed');
  await expect(page.getByRole('table', { name: 'Expected and actual outcomes' })).toBeVisible();
  const prompt = f.pkg.files.find(file => file.path.endsWith('/review.md'))!;
  await writeFile(join(f.repository, prompt.path), prompt.text + '\nCheck the boundary condition.\n');
  await expect(page.locator('#result')).toContainText('Files changed.', { timeout: 10_000 });
  await page.locator('#simulate').click(); await expect(page.locator('#result')).not.toContainText('Files changed.');
  await writeFile(f.workflow, '{ invalid');
  await expect(page.locator('#diagnostics')).toBeVisible({ timeout: 10_000 });
  await expect(page.locator('#simulate')).toBeDisabled(); await expect(page.locator('#result')).toContainText('Files changed.');
  assert.equal(await readFile(f.workflow, 'utf8'), '{ invalid');
  await writeFile(f.workflow, JSON.stringify(f.pkg.workflow));
  await expect(page.locator('#diagnostics')).toBeHidden({ timeout: 10_000 });
  await command('simulate', '--capture', f.capture.directory);
  await expect(page.locator('#pr-mode')).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('#input-summary')).toContainText('willow-labs/sample-project #42');
  await expect(page.locator('#input-note')).toContainText('Current GitHub state has not been checked.');
  await expect(page.locator('#input-note')).toContainText('earlier workflow');
  if (proof) await page.screenshot({ path: join(proof, 'captured-pr.png'), fullPage: true });
  await page.locator('#tests-mode').click(); await expect(page.locator('#result')).toContainText('Test passed');
  await page.locator('#overview-tab').focus(); await page.keyboard.press('Enter'); await expect(page.locator('#overview')).toBeVisible();
  const alternate = 'another.workflow.json'; await writeFile(join(f.repository, alternate), await readFile('skills/repo-chap-workflows/assets/workflow.json', 'utf8'));
  await expect(page.locator('#workflow-select option')).toHaveCount(2, { timeout: 10_000 });
  await page.locator('#workflow-select').selectOption(alternate); await expect(page.locator('#workflow-select')).toHaveValue(alternate);
  assert.equal((await command('status')).simulation, null);
  for (const [width, height] of [[1024, 768], [390, 844]]) {
    await electron.evaluate(({ BrowserWindow }, bounds) => BrowserWindow.getAllWindows()[0]!.setBounds(bounds), { width, height });
    await expect.poll(() => page.evaluate(() => innerWidth)).toBe(width);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1));
    if (width === 390) {
      await command('show', '--target', 'rule:closed');
      await expect(page.locator('[data-target="rule:closed"]')).toHaveAttribute('open', '');
      const explanation = (await page.locator('.canvas-inspector').boundingBox())!;
      assert.ok(explanation.x >= 0 && explanation.x + explanation.width <= width);
    }
    if (proof) await page.screenshot({ path: join(proof, `overview-${width}.png`), fullPage: true });
  }
  assert.deepEqual(errors, []); assert.deepEqual(requests, []);
  await expect.poll(async () => JSON.parse(await readFile(join(f.data, 'companion/selection.json'), 'utf8')).workflowPath).toBe(alternate);
  await electron.close();
  electron = await launch(); page = await electron.firstWindow();
  await expect(page.locator('#workflow-select')).toHaveValue(alternate);
  assert.equal((await command('status')).workflowPath, alternate);
  await electron.close();
});

test('an empty repository discovers the agent-created workflow and a cancelled picker preserves selection', { timeout: 40_000 }, async t => {
  const f = await companionFixture(); t.after(f.cleanup);
  const empty = join(f.temporary, 'new-project'); await mkdir(empty);
  const electron = await _electron.launch({ executablePath, args: packaged ? [] : [resolve('apps/desktop')], env: { ...process.env, REPO_CHAP_DESKTOP_CONTROL: f.control, REPO_CHAP_DESKTOP_DATA: f.data } });
  t.after(() => electron.close()); const page = await electron.firstWindow();
  await page.evaluate(async root => window.repoChap.command({ kind: 'open', repositoryRoot: root }), empty);
  await expect(page.locator('#empty')).toBeVisible();
  await expect(page.locator('#empty')).toContainText('No workflows yet');
  await expect(page.locator('#repository-name')).toHaveText('new-project');
  await expect(page.locator('#open-repository')).toHaveAttribute('aria-label', 'Change repository');
  await expect(page.locator('#worktree-name')).toBeHidden();
  await page.locator('#empty-add').click();
  await expect(page.locator('#add-workflow-dialog')).toBeVisible();
  await expect(page.locator('#agent-request')).toContainText('$repo-chap-workflows');
  await page.locator('#copy-agent-request').click();
  await expect(page.locator('#copy-status')).toHaveText('Request copied.');
  assert.match(await electron.evaluate(({ clipboard }) => clipboard.readText()), /new-project/);
  await page.keyboard.press('Escape');
  await assert.rejects(readFile(join(empty, 'workflow.json')));
  const git = (...args: string[]) => promisify(execFile)('git', ['-C', empty, ...args]);
  await git('init');
  await git('-c', 'user.name=Willow', '-c', 'user.email=willow@example.invalid', 'commit', '--allow-empty', '-m', 'Initial commit');
  const worktree = join(f.temporary, 'agent-checkout');
  await git('worktree', 'add', '-b', 'agent-work', worktree);
  await page.evaluate(async root => window.repoChap.command({ kind: 'open', repositoryRoot: root }), worktree);
  await expect(page.locator('#repository-name')).toHaveText('new-project');
  await expect(page.locator('#worktree-name')).toHaveText('Worktree: agent-checkout');
  for (const width of [720, 390]) {
    await electron.evaluate(({ BrowserWindow }, width) => BrowserWindow.getAllWindows()[0]!.setBounds({ width, height: 800 }), width);
    await expect(page.locator('#repository-name')).toBeVisible();
    await expect(page.locator('#worktree-name')).toBeVisible();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    if (process.env.REPO_CHAP_DESKTOP_PROOF) await page.screenshot({ path: join(process.env.REPO_CHAP_DESKTOP_PROOF, `empty-worktree-${width}.png`), fullPage: true });
  }
  await page.evaluate(async root => window.repoChap.command({ kind: 'open', repositoryRoot: root }), empty);

  await writeFile(join(empty, 'workflow.json'), await readFile('skills/repo-chap-workflows/assets/workflow.json', 'utf8'));
  await expect(page.locator('#workflow-select')).toHaveValue('workflow.json', { timeout: 10_000 });
  await electron.evaluate(({ dialog }) => { dialog.showOpenDialog = async () => ({ canceled: true, filePaths: [] }); });
  await page.locator('#open-repository').click(); await expect(page.locator('#workflow-select')).toHaveValue('workflow.json');
});
