#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.

# This is a repeatable operator path, so it lives with the pilot code.
TOTAL_STAGES=5
TOTAL_MINUTES=25

WORKSPACE_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$WORKSPACE_ROOT"

banner "Repo Chap test environment"

stage "Local tools" 2
say "The pilot uses the repository-pinned build plus Terraform, GitHub CLI, Tailscale, OpenSSH, and tar."
for tool in vp terraform gh tailscale ssh tar codex; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    warn "$tool is missing from PATH"
    exit 1
  fi
done
gh auth status
tailscale status >/dev/null
say "Local tools and account sessions are available."

stage "Private repository and daemon files" 7
open_url "https://github.com/settings/apps"
step "Use a dedicated private test repository and a GitHub App installed only on that repository."
step "Prepare a flat mode-0700 directory containing mode-0600 installation.json, providers.json, the App PEM, and a Slack bot token. Pilot generates its repair policy."
ask REPOSITORY "Private repository (owner/name):"
ask PILOT_PROFILE "Provider profile name:"
ask SLACK_WORKSPACE "Slack workspace ID:"
ask SLACK_CHANNEL "Dedicated Slack channel ID:"
ask CONFIG_DIRECTORY "Absolute private daemon configuration directory:"
[[ "$CONFIG_DIRECTORY" = /* && -d "$CONFIG_DIRECTORY" && -f "$CONFIG_DIRECTORY/installation.json" ]] || {
  warn "The configuration directory or installation.json is missing."
  exit 1
}

stage "Dedicated Codex login" 5
say "Use a dedicated CODEX_HOME. The normal Codex cache is never copied."
ask PILOT_CODEX_HOME "Absolute dedicated CODEX_HOME:"
[[ "$PILOT_CODEX_HOME" = /* ]] || { warn "CODEX_HOME must be absolute."; exit 1; }
if [[ ! -f "$PILOT_CODEX_HOME/auth.json" ]]; then
  step "Complete the normal Codex login in this dedicated directory."
  CODEX_HOME="$PILOT_CODEX_HOME" codex login
fi
[[ -f "$PILOT_CODEX_HOME/auth.json" ]] || { warn "Codex authentication was not created."; exit 1; }

stage "Cloud and tailnet credentials" 7
open_url "https://cloud.digitalocean.com/account/api/tokens"
step "Create or select a scoped DigitalOcean token for this disposable environment."
ask_secret DIGITALOCEAN_TOKEN "DigitalOcean token:"
open_url "https://login.tailscale.com/admin/settings/oauth"
step "Use an OAuth client limited to auth_keys and devices:core for tag:repo-chap-pilot."
ask TAILSCALE_CLIENT_ID "Tailscale OAuth client ID:"
ask_secret TAILSCALE_CLIENT_SECRET "Tailscale OAuth client secret:"
step "Confirm the tailnet policy grants your identity SSH access to tag:repo-chap-pilot as pilot-diagnostic."
pause "Press Enter after checking the policy."

stage "Create environment" 4
ask OPERATOR_ROOT "Absolute private operator directory:"
ask REGION "DigitalOcean region [ams3]:"
REGION=${REGION:-ams3}
ask SIZE "DigitalOcean size [s-2vcpu-4gb]:"
SIZE=${SIZE:-s-2vcpu-4gb}
[[ "$OPERATOR_ROOT" = /* ]] || { warn "The operator directory must be absolute."; exit 1; }
write_env REPO_CHAP_PILOT_ROOT "$OPERATOR_ROOT"
if ! DIGITALOCEAN_KEY_OUTPUT=$(vp exec node deploy/pilot/digitalocean-key.mjs --root "$OPERATOR_ROOT"); then
  warn "Could not prepare the local DigitalOcean SSH key."
  exit 1
fi
DIGITALOCEAN_SSH_KEY_FINGERPRINT=$(printf '%s\n' "$DIGITALOCEAN_KEY_OUTPUT" | sed -n '1p')
DIGITALOCEAN_SSH_PUBLIC_KEY_FILE=$(printf '%s\n' "$DIGITALOCEAN_KEY_OUTPUT" | sed -n '2p')
step "Register this public key with DigitalOcean: $DIGITALOCEAN_SSH_PUBLIC_KEY_FILE"
open_url "https://cloud.digitalocean.com/account/security"
pause "Press Enter after registering the public key."
OPERATOR_ROOT="$OPERATOR_ROOT" REPOSITORY="$REPOSITORY" REGION="$REGION" SIZE="$SIZE" \
DIGITALOCEAN_SSH_KEY_FINGERPRINT="$DIGITALOCEAN_SSH_KEY_FINGERPRINT" \
CONFIG_DIRECTORY="$CONFIG_DIRECTORY" PILOT_CODEX_HOME="$PILOT_CODEX_HOME" \
PILOT_PROFILE="$PILOT_PROFILE" SLACK_WORKSPACE="$SLACK_WORKSPACE" SLACK_CHANNEL="$SLACK_CHANNEL" \
  vp node --input-type=module -e '
    import { join } from "node:path";
    import { privateDirectory, writePrivate } from "./deploy/pilot/store.mjs";
    const value = {
      repository: process.env.REPOSITORY,
      region: process.env.REGION,
      size: process.env.SIZE,
      digitalOceanSshKeyFingerprint: process.env.DIGITALOCEAN_SSH_KEY_FINGERPRINT,
      configDirectory: process.env.CONFIG_DIRECTORY,
      codexHome: process.env.PILOT_CODEX_HOME,
      pilotConfig: { profile: process.env.PILOT_PROFILE, workspaceId: process.env.SLACK_WORKSPACE, channelId: process.env.SLACK_CHANNEL }
    };
    const root = process.env.OPERATOR_ROOT;
    await privateDirectory(root, true);
    await writePrivate(join(root, ".gitignore"), "*\n");
    await writePrivate(join(root, "operator.json"), JSON.stringify(value, null, 2) + "\n");
  '
if CREATE_OUTPUT=$(DIGITALOCEAN_TOKEN="$DIGITALOCEAN_TOKEN" \
    TAILSCALE_CLIENT_ID="$TAILSCALE_CLIENT_ID" TAILSCALE_CLIENT_SECRET="$TAILSCALE_CLIENT_SECRET" \
    REPO_CHAP_PILOT_ROOT="$OPERATOR_ROOT" vp run pilot create); then
  printf '%s\n' "$CREATE_OUTPUT"
else
  CREATE_STATUS=$?
  printf '%s\n' "$CREATE_OUTPUT"
  warn "Creation failed. The environment may still bill until deletion succeeds."
  exit "$CREATE_STATUS"
fi
ENVIRONMENT_ID=$(printf '%s\n' "$CREATE_OUTPUT" | sed -n 's/^done - id: \([a-f0-9]\{24\}\)$/\1/p' | tail -n1)
[[ -n "$ENVIRONMENT_ID" ]] || { warn "Could not read the environment ID."; exit 1; }
finish
say "Environment: $ENVIRONMENT_ID"
say "Operator directory: $OPERATOR_ROOT"
warn "This wizard did not save cloud or tailnet credentials."
say "Load DIGITALOCEAN_TOKEN, TAILSCALE_CLIENT_ID, and TAILSCALE_CLIENT_SECRET from your secret manager before later commands."
say "Next: vp run pilot test --environment $ENVIRONMENT_ID"
