import type { PacketPreview } from './types.js';

const html = (text: string): string => text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
export function previewHtml(preview: PacketPreview): string {
  const destination = preview.route.destination;
  const route = destination?.kind === 'dm' ? `DM to ${destination.authorLogin} · ${destination.memberId}` : destination ? `${destination.name} · ${destination.channelId}` : 'CLI inbox only';
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Local Slack preview</title><style>
:root{color-scheme:light;font-family:system-ui,sans-serif;color:#604939;background:#F2EADE;font-size:16px;line-height:1.6}*{box-sizing:border-box}body{margin:0;padding:clamp(16px,4vw,48px)}main{max-width:760px;margin:auto}h1{font-size:clamp(28px,4vw,36px);font-weight:600;letter-spacing:-.015em;line-height:1.2;margin:0 0 12px}h2{font-size:22px;font-weight:600;margin:0 0 8px}p{margin:0 0 16px}header{margin-bottom:24px}.secondary{font-size:13.5px;color:#66574D}.destination{font-weight:600;margin-bottom:4px}.notice{padding:12px 16px;border-left:3px solid #784F26;background:#EADFCD;margin:16px 0}article{background:#EADFCD;border-radius:12px;padding:clamp(16px,4vw,32px)}dl{margin:24px 0 0}dt{font-weight:600;margin-top:20px}dd{margin:4px 0 0;white-space:pre-wrap;overflow-wrap:anywhere;max-width:70ch}a{color:#3D5D71;text-decoration-thickness:1.5px;text-underline-offset:3px}nav{display:flex;gap:12px 20px;flex-wrap:wrap;margin-top:24px}a:focus-visible,summary:focus-visible{outline:3px solid #3D5D71;outline-offset:5px;border-radius:3px}details{margin:24px 0}summary{cursor:pointer;color:#3D5D71;text-decoration:underline;text-underline-offset:3px}pre{font:inherit;white-space:pre-wrap;overflow-wrap:anywhere;padding:16px;background:#EADFCD;border-radius:8px}.metadata{white-space:pre-wrap;overflow-wrap:anywhere}.mentions{margin-top:16px}@media(max-width:440px){body{padding:16px}article{padding:16px}nav{display:grid}}
</style></head><body><main>
<header><p class="secondary">Repo Chap · Offline renderer</p><h1>Local Slack preview</h1><p>No message was sent. Slack client rendering and account delivery still need pilot verification.</p><p class="destination">${html(route)}</p><p class="secondary">${html(preview.route.workspaceId ?? 'No workspace configured')}</p>${preview.route.fallback || !destination ? `<p class="notice">${html(preview.route.explanation)}</p>` : ''}</header>
<article aria-label="Proposed Slack message"><h2>${html(preview.sections[0]!.heading)}</h2><p class="metadata">${html(preview.sections[0]!.text)}</p><dl>${preview.sections.slice(1).map(section => `<dt>${html(section.heading)}</dt><dd>${html(section.text)}</dd>`).join('')}</dl><nav aria-label="GitHub evidence">${preview.links.map(link => `<a href="${html(link.url)}" rel="noreferrer">${html(link.label)}</a>`).join('')}</nav>${preview.route.mentions.length && !preview.superseded ? `<p class="mentions">Configured mentions: ${preview.route.mentions.map(html).join(', ')}</p>` : ''}</article>
<details><summary>Read the accessible text fallback</summary><pre>${html(preview.message.text)}</pre></details>
</main></body></html>`;
}
